version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"

  build:
    commands:
      - echo "Preparing deployment artifact..."
      - chmod +x script/*.sh

artifacts:
  files:
    - '**/*'
