export enum StorageKey {
  AUTH_TOKEN = "ott_auth_token",
  REFRESH_TOKEN = "ott_refresh_token",
  SESSION_ID = "ott_session_id",
  DEVICE_ID = "ott_device_id",
  THEME = "ott_theme",
  LOCALE = "ott_locale",
  WATCH_HISTORY = "ott_watch_history",
  VOLUME = "ott_volume",
  SOCKET_LOCK = "ott_active_socket_session",
  GEO_CACHE = "ott_geo_cache",
  SELECTED_PROFILE = "ott_selected_profile",
  BROWSER_UID = "browser_uid",
  APPLE_AUTH_STATE = 'apple_auth_state',
  IS_REGISTER = "isRegister",
  ID_TOKEN = "id_token",
  CODE = "code",
  STATE = 'state',
  ERROR = 'error',
  USER = 'user',
  COUNTRY_LIST_DATA = "ott_country_list_data",
  COUNTRY_LIST_TIMESTAMP = "ott_country_list_timestamp",

  // Player
  PLAYER_VOLUME = "ott_player_volume",
  PLAYER_SPEED = "ott_player_speed",
  PLAYER_CAPTION_SIZE = "ott_player_caption_size",
  PLAYER_CAPTION_FONT_SIZE = "ott_player_caption_font_size",
  PLAYER_CAPTION_TEXT_COLOR = "ott_player_caption_text_color",
  PLAYER_CAPTION_BG_COLOR = "ott_player_caption_bg_color",
  PLAYER_CAPTION_BG_OPACITY = "ott_player_caption_bg_opacity",
  RECENT_SEARCHES = "ott_recent_searches"
}
